### ISSUE TITLE
Backend - Files count in files.js - unused? incorrect?

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#1026]
The function countInProject in files.js, in the backend code, appears to not be used. Specifically, files in the demo project, at this time, do not have a project_id field, and that field is not in the file specification in the object model, model.js -- no UI errors were found for the demo project and the project appears to be getting file counts from the function addComputed in project.js. Further investigation is needed, but is is likely that this function should be modified or removed.

**Comment by gtarcea** [comment]
Delete countInProject method in db/model/files.js

**Comment by Terry-Weymouth** [comment]
Put a condition <div> in when the note list was empty and this solved the problem.
