### ISSUE TITLE
Assignable access controls for who can edit templates

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#1042]
Add access controls to limit who can edit templates; see also #1083 (Templates can be edited by anyone! Restrict) and note on it below.

**Comment by Terry-Weymouth** [comment]
A version of this has been completed. See issue #1083.  The initial version, already implemented, restricts access to the creator of the template (designated as the 'owner') and/or anyone with template_admin access. The initial template set, loaded at system start, are all marked as being owned by 'template-admin' a non-email owner; to avoid the possibility of accidental ownership.

A more complete "access control list" type of access is probably desirable, so I am leaving this issue open to represent that approach.
