### ISSUE TITLE
File directory structure is hard to view/use

### ISSUE THREAD

**Issue by tradiasa** [materials-commons/materialscommons.org#1086]
Perhaps should be broken into multiple tickets

- can't drag and drop multiple files into a folder (each needs to be done individually)
-no way to sort files/folders 
-hard to view structure (nested folders)
-can't tell if I'm succeeding in uploading multiple files through the UI (at the same time or not)
-would like to be able to drag file structure wider - wrapping of the file name makes it hard to view the structure

User story: Tracy is trying to share all of her raw EPMA data with Zhenjie.  Neither Zhenjie or Tracy can figure out if all of the files are on MC or not without checking one by one.  Tracy copies folder containing all EPMA data into Box because it's easier.

**Comment by Terry-Weymouth** [comment]
@tradiasa - Tracy, I saw this and am reviewing it. Will also discuss with Glenn (@gtarcea). Probably, as you suggest, we will brake into individual improvement-suggestions, especially as some of these are already in separate issues.

**Comment by gtarcea** [comment]
The original fix was to address file uploading/downloading crashes. There were a number of other issues I encountered. Below is the full list of things I fixed:

    * Viewing published files was failing because access controls weren't checking if a files was published
    * Chrome would not display PDF files
    * The file converter was not being run in all cases. This meant that users couldn't reliably view office and TIFF files in the website
    * Update file uploader to use a new file upload component that allows:
        * Files to be dragged/dropped on to the upload
        * Previews of images
        * Cleans up the workflow for file uploads
        * Performs simultaneous file uploads (in batches of size 3)
    * Integrate new uploader into process file uploads
    * Fix batch downloading files (select files to download, build a zip file, and allow the zip file to be downloaded with all the files selected)
    * File tree was not updating when files were uploaded, making it look like the upload didn't succeed
    * File tree was not updating when creating a directory, making it seem like the directory wasn't created
    * File tree was not updating when renaming a directory, making it appear that the directory had two different names
    * File tree was not updating when deleting a file or directory, making it seem like the directory or file wasn't deleted
    * Moving a file or directory in the tree often didn't work, and was very difficult to get correct
    * When in sub directory there was no way to display the root
    * Deleting files/directories didn't ask the user if they really wanted to perform the delete
    * Incorrect HTTP headers were returned on file download/view causing the view to fail in many instances

All in all this involved changes in 55 files. This was code that hadn't been touched since August of 2016. I had to upgrade various packages we depended on, install new ones, convert code to work with the packages.
