### ISSUE TITLE
Public data site, user logged out, Unauthorized Errors

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#1171]
When public data site pages are constructed, there are several REST calls that are made back to the  private project site. If the user is not logged in, these are getting a Not Authorized error. I suspect that they are call related to workflow and files. As there are no obvious effects of these errors on the viewing of the public data, this is not a critical problem. However, it does "clog up" the log file and it would be a good idea to catch the requests before they are made and simply not make the related REST calls.

It should be easy to figure out what REST path is being requested (at the mcapi REST server), backtrace to where those REST calls are made, and disable them in the case the user is not logged in (or remove them entirely).

**Comment by gtarcea** [comment]
ng-src was being used on <img> tag to show images but wasn't checking if user was authenticated. Wrapped the div in an ng-if check that includes checking authentication so that images aren't accessed when user isn't logged.
