### ISSUE TITLE
Italics, bold, and strikethrough don't work in Project Notes

### ISSUE THREAD

**Issue by stvdwtt** [materials-commons/materialscommons.org#1264]
It seems like the standard markdown syntax for italics, bold, and strikethrough don't work in the Notes. This isn't a huge deal, but is kind of surprising.

**Comment by Terry-Weymouth** [comment]
Steve, If you still having problems with this issue, let me know.

I tested these in the production install of the code (that is the current master branch, at commit f15cf216888142801588be9a7fc3eb719ae1411d ) and I can not reproduce the error. I tested the following: underscore/asterisk for italics, double underscore/asterisk for bold, and double tilde for strikethrough, as per the link at the head of the edit box for notes. This should also be true in LIFT and on the test version of materials commons. I am closing this issue.
