### ISSUE TITLE
Display all experiments (regardless of state)

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#698]
I think that All experiments should be displayed, as least by default, perhaps a Hide/Show option which indicated which state it is in for each type. It's unnerving to have the experiment vanish from the screen when it changes state.

**Comment by gtarcea** [comment]
There seems to be a few different items listed here. For example, we could fade out or fade in experiments. This would take care of the "unnerving" issue.

Lets ask our users about this.
