### ISSUE TITLE
Add "report a problem" link to the projects websites

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#701]
Create a prominent, always-on-the-view, link for "report a problem". Using mail-to help@materialscommons.org (??). Add to the projects website.

**Comment by Terry-Weymouth** [comment]
I've created a mail group, and therefor an email address, at materials-commons-help@umich.edu as the target for this link (e.g. 'mailto:') - @gtarcea and I are the initial members, owners of the group. Obviously, it should be set up as an environment variable (e.g. system parameter), with this value as a (possible) default - another possible default could be empty and have the link display a error (toast) popup if not set.

**Comment by Terry-Weymouth** [comment]
Use help@materialscommons.org, instead. This one works.

**Comment by gtarcea** [comment]
Added link to the project bar.
