### ISSUE TITLE
Materials Commons Data site Downloads

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#707]
Currently downloads of datasets on Materials Commons Data is not working. The site should allow a zip file of the dataset to be downloaded.

We should consider if the zipfile should be pre-generated or created on the fly.

**Comment by Terry-Weymouth** [comment]
This issue fixed at commit 7f9c3bdf1506b85e4f651bddb95daca4d3b5ee73 but issues remain as indicated in issues #721 #732 and #733. Closing this issue in favor of the more detailed issues on remaining bugs.
