### ISSUE TITLE
Publish site: search needs additional small changes.

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#725]
There may be a problem with the search index???

**Comment by Terry-Weymouth** [comment]
@gtarcea got basic search working: case-insensitive match only (on all fields) - Need to add search on fields and update UI with submit button (in addition to CR-based submit).

**Comment by gtarcea** [comment]
Limited the choices to all. Will close this and open an issue to allow searches on other fields.
