### ISSUE TITLE
Dataset publishers are displayed as an email address rather than their name

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#728]
Published datasets show the publisher as an email address. This exposes the email address (which may not be wanted) and requires users to know email addresses (not just names).

**Comment by Terry-Weymouth** [comment]
There is now a script in the backend/scripts/conversions folder called add_fullname.py which will take a file of (tab-seperated) e-mail and fullname values and update the fullname in the users table for e-mail address that do not already have a full name (or where the full name is the e-mail - which seems to be, more likely, the case)
