### ISSUE TITLE
When publishing a dataset the files associated with the samples are not in the sample2datafile table

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#734]
Published datasets copy all the information associated with the items in the dataset. The entries in the sample2datafile table are not saved, so published datasets do not save the association of files to their samples.

This means that the provenance outline in the published data site cannot show the files for a sample.

**Comment by Terry-Weymouth** [comment]
Actually, I made a mistake - this issues is NOT RELATED to #733 - but I don't know how to undo that comment - above.
