### ISSUE TITLE
Publish site: When a tag is associated with zero datasets it should be removed

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#751]
Currently there is no way to remove a tag. If you remove all the tag from all datasets it will still show up in the list of tags on the home page. This means that the list gets filled with tags that don't lead to any datasets.

**Comment by Terry-Weymouth** [comment]
For now, I just filtered out the zero-count tags on fetch all tags, this will suffice for the current UI. Obviously a work-around until we design a better place, time, method for removing the zero-count tags. Probably should be a remove tag (list) service. See also #742.

**Comment by Terry-Weymouth** [comment]
Completed this task (see commit https://github.com/materials-commons/materialscommons.org/commit/0e61fe0a519e78afc87c2ec0bb81b873cb51e7a7). When a tag is deleted from the dataset, if it has no additional datasets associations, it is then deleted.
