### ISSUE TITLE
Collecting and Analyzing stats for MC sites

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#771]
We need to include user/usage stats collection and analysis for the materials commons sites. I propose that we use Google Analytics (see: https://www.google.com/analytics/#/small-business )

**Comment by gtarcea** [comment]
Analytics we need to collect:
* New users over some time frame
* File uploads
* Total file space
* Published datasets
* Collaborators
* Number of new projects
* Downloads
* Views on the data site

Derived statistics we would like:
* How often people are logged into Materials Commons
