### ISSUE TITLE
Can not add sample in Project's Samples table

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#815]
In the project display, click on the SAMPLES tab, then in the results samples table, click on the + NEW SAMPLES button. One gets an error message "Error: unable to add samples".

**Comment by Terry-Weymouth** [comment]
@gtarcea (see above) - should be button be disabled for this release (leaving the issue open)?

**Comment by gtarcea** [comment]
Removed ability to add samples in the table.
