### ISSUE TITLE
Need a zipfile builder that runs "in the background".

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#846]
The zipfile building process (part of dataset publication) can take minutes to complete. So, it needs to run as a "background" task: publication sets a flag, the flag setting triggers the build, when the build is complete, and other flag is set to indicate that the zip file is built. The UI in data set needs to be changed so that the different starts of the zip files are reflected:
Unavailable - no build requested
Unavailable - build requested, but not completed
Available - build complleted
Also, it might be a good idea to have an option to rebuild the zip file.
(see commented out call to publishDatasetZipFile in backend/servers/mcapi/db/model/experiment-datasets.js)

**Comment by gtarcea** [comment]
Duplicate
