### ISSUE TITLE
Removed unused tables from materialscommons database

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#870]
There are old unused tables in the database that could be deleted. It would also require updating dbcreate.py to not build the tables and indices.

A preliminary list of tables to delete include:
**Note**: This is for the **materialscommons** database and **not** the mcpub database.
comment2item
machines (might want to keep for future reintroduction)
1. note2item
2. notes
3. review2item
4. reviews
5. runs
6. tag2item
7. tags
8. ui
9. usergroups

**Comment by Terry-Weymouth** [comment]
@gtarcea I would like to be able to check and determine that a table is being used. Where do I need to look? Is this sufficent? Search "all *.js in backend and all *.py in backend" for TableName?

**Comment by gtarcea** [comment]
Yes. Search for .table
