### ISSUE TITLE
Project 'home' page does not scroll experiment list.

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#880]
When there are more the 3 or 4 experiments in a project, the list "falls off" the end of the page and there is no scroll bar to enable viewing of them.

**Comment by Terry-Weymouth** [comment]
This still has problems: see commit (https://github.com/materials-commons/materialscommons.org/commit/7b25b97b2f92a19dc74e86a8e980253bd4fe894f) which I thought was working, but in latest sprint (https://github.com/materials-commons/materialscommons.org/commit/ecc43ecd619cd7d824800d3bb35c2820f1c96cd5) is is not. ???

**Comment by gtarcea** [comment]
Fixed in general fix for scrolling.
