### ISSUE TITLE
CPFE Template

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#884]
See also #885 for complex types 'Mesh', 'Solver', 'Finite Element Basis'

Crystal Plasticity Finite Element (Process):
- Finite Element Basis:
  - type: 'Finite Element Basis'
- Mesh
  - type: Mesh
- Linear Solver:
  - type: Solver
- Nonlinear Solver:
  - type: Solver

**Comment by bpuchala** [comment]
The input to a CPFE process is a "Sample" that specifies a particular material. The required material parameters are below.

Where 'units: Pa' is indicated, should allow "MPa" or "GPa"

CPFE Sample Attributes:
- Crystal Type
  - name: crystal_type
  - enum: ["fcc", "bcc", "hcp"]
- Latent Hardening Ratio
  - name: latent_hardening_ratio
  - type: float
- Number of Slip Systems
  - name: num_slip_systems
  - type: integer
- Initial Slip Resistance
  - required_if: num_slip_systems > 0
  - name: initial_slip_resistance
  - desc: "Critical resolved shear stress of slip systems"
  - type: float
  - dim: [num_slip_systems]
  - units: Pa
- Initial Hardening Modulus
  - required_if: num_slip_systems > 0
  - name: initial_hardening_modulus
  - desc: "Hardening moduli of slip systems"
  - type: float
  - dim: [num_slip_systems]
  - units: Pa
- Power Law Exponent
  - required_if: num_slip_systems > 0
  - name: power_law_exponent
  - desc: "Power law coefficient"
  - type: float
  - dim: [num_slip_systems]
- Saturation Stress
  - required_if: num_slip_systems > 0
  - name: initial_hardening_modulus
  - desc: "Saturation stress"
  - type: float
  - dim: [num_slip_systems]
  - units: Pa
- Elastic Stiffness
  - name: elastic_stiffness
  - type: float
  - dim: [6, 6]
  - unit: Pa

- Number of Twin Systems
  - name: num_twin_systems
  - type: integer
- Initial Twin Slip Resistance
  - required_if: num_twin_systems > 0
  - name: initial_slip_resistance
  - desc: "Critical resovled shear stress of twin systems"
  - type: float
  - dim: [num_twin_systems]
  - units: Pa
- Initial Twin Hardening Modulus
  - required_if: num_twin_systems > 0
  - name: initial_hardening_modulus
  - desc: "Hardening moduli of twin systems"
  - type: float
  - dim: [num_twin_systems]
  - units: Pa
- Twin Power Law Exponent
  - required_if: num_twin_systems > 0
  - name: power_law_exponent
  - desc: "Power law coefficient"
  - type: float
  - dim: [num_twin_systems]
- Twin Saturation Stress
  - required_if: num_twin_systems > 0
  - name: initial_hardening_modulus
  - desc: "Saturation stress"
  - type: float
  - dim: [num_twin_systems]
  - units: Pa
- Twin Shear
  - required_if: num_twin_systems > 0
  - name: twin_shear
  - desc: "Characteristic twin shear"
  - type: float
- Twin Threshold Fraction
  - required_if: num_twin_systems > 0
  - name: twin_threshold_fraction
  - desc: "Threshold fraction of characteristic twin shear"
  - type: float
  - validate: twin_threshold_fraction < 1.0
- Twin Saturation Factor
  - required_if: num_twin_systems > 0
  - name: twin_saturation_factor
  - desc: "Twin growth saturation factor"
  - type: float
