### ISSUE TITLE
Phase Field Template

### ISSUE THREAD

**Issue by bpuchala** [materials-commons/materialscommons.org#886]
See also #885 for complex types

Phase Field Calculation (Process):
- Finite Element Basis:
  - type: 'Finite Element Basis'
- Mesh
  - type: Mesh
- Mesh Adaptivity:
  - type: Mesh Adaptivity Parameters
- Mechanics Solver:
  - type: Solver

**Comment by bpuchala** [comment]
Inputs to Phase Field calculations involve parameters are broken into three parts: "Single Phase" (for bulk single phase properties), "Phase Interface" (describes pairwise interactions and interpolations), and "Phase Field System" (describes global coupling). These can then be combined to form the input to a Phase Field calculation.

For now, treat the properties with type "function" as string.

Single Phase (Sample Attributes):
- Name:
  - name: phase_name
  - type: string
- Application:
  - type: string
  - desc: "Describes the physical model"
  - ex: "CahnHilliard", "AllenCahn", "CoupledCahnHilliardAllenCahn", etc.
- Cahn-Hilliard parameters:
  - required_if: Application includes CahnHilliard
  - Source: 
    - type: function
  - Homogeneous Free Energy Density:
    - name: homogeneous_free_energy_density
    - type: function
  - Concentration Gradient Penalty Coefficient
    - dim: [3] or [3,3]
    - type: float
  - Cahn-Hilliard Mobility
    - name: cahn_hilliard_mobility
    - type: float
- Linear Elasticity Mechanics Parameters:
  - required_if: Application includes linear elasticity
  - Lattice
    - name: lattice
    - dim: [3, 3]
    - type: float
  - Symmetry of the Stiffness Tensor
    - name: stiffness_symmetry
    - enum: ["isotopic", "anisotropic", "transverse", "orthotropic"]
  - Stiffness Tensor
    - name: stiffness
    - desc: "anisotropy.h"
    - dim: {"isotropic" & 1d:[1], 2d:[2], 3d:[2]}, {"anisotropic" & 2d:[6], 3d:[21]}, {"transverse" & 3d:[5]}, {"orthotropic" & 3d:[9]}
    - type: float


Phase Interface (Sample Attributes):
- Phases:
  - dim: [2]
  - desc: "The phases separated by this interface"
  - type: string
- Model:
  - name: phase_field_model
- Allen-Cahn Mobility
    - name: allen_cahn_mobility
    - type: float (isotropic), generally function
- Structural Order Parameter Gradient Penalty Coefficient
  - dim: [3] or [3,3]
  - type: float

**Comment by bpuchala** [comment]
Phase Interface (Sample Attributes):
- Phases:
  - dim: [2]
  - desc: "The phases separated by this interface"
  - type: string
- Model:
  - name: phase_field_model
- Allen-Cahn Mobility
    - name: allen_cahn_mobility
    - type: float (isotropic), generally function
- Structural Order Parameter Gradient Penalty Coefficient
  - dim: [3] or [3,3]
  - type: float

**Comment by bpuchala** [comment]
The relevant sample attributes will vary depending on the physical model...

Phase Field System (Sample Attributes):
- Application:
  - type: string
  - desc: "Describes the physical model"
  - ex: "CahnHilliard", "AllenCahn", "CoupledCahnHilliardAllenCahn", etc.
- Interpolation Function:
  - required_if: (particular types)
  - type: function

**Comment by johnallison** [comment]
Interesting - so a sample is a phase or a phase boundary, right?
thanks
john
John Allison
Professor, Materials Science and Engineering
Director, UM Center for PRedictive Integrated Structural Materials Science (PRISMS)
734-615-5150
PRISMS Center Website: http://prisms-center.org
