### ISSUE TITLE
Account Settings fails to load projects

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#890]
Under the user name pulldown, after login (upper right). There is an attempt to pull down the list of projects (presumable to fill in the Default Project pull down) that is failing - with the following message in the Javascript console: http://mctest.localhost/api/projects?apikey=***

This fails!

However, the URL used on the top-level MC page is ok: 
http://mctest.localhost/api/v2/projects?apikey=***

So, apparently this call in account settings needs to be changes.

**Comment by gtarcea** [comment]
The projectsService in the UI was updated to go to the correct backend. However the old calls were still in place and used in some instances. I updated all instances to use the new API and removed references to calls that go to the old REST route.
