### ISSUE TITLE
LIFT deployment

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#908]
A new MC server is needed for the LIFT project.

**Comment by gtarcea** [comment]
- [ ] Get domain name for lift.materialscommons.org
- [ ] Configure NGINX with key files for lift.materialscommons.org
- [ ] Setup NFS mount for TurboStorage
- [ ] Request admin (sudo) account for Terry Weymouth on lift server
- [X] Build mcstored
- [ ] Resolve external firewall issues for lift server
- [ ] Resolve internal se-linux issues for lift server
- [ ] Install Tika

**Comment by gtarcea** [comment]
Server deployed. No persistent connection to Turbo.
