### ISSUE TITLE
Needs to be reviewed - UI comments - review (and split?)

### ISSUE THREAD

**Issue by bpuchala** [materials-commons/materialscommons.org#911]
* must manually update samples list when samples are created
* create samples: let indices begin at 0
* must manually refresh to get edges in workflow graph
* create samples, add input samples (i.e. created configurations depends on the prim)
* computational processes file under "Measurements"
* edit process date?
* samples as nodes in workflow graph?
* save workflow graph state after dragging elements around

**Comment by Terry-Weymouth** [comment]
These issues may need to be split out into separate issues. Also, some imply design changes. Probably need to evaluate those.

**Comment by Terry-Weymouth** [comment]
This needs to be reviewed (in consort with the other issues in it's epic) - review scheduled for June.
