### ISSUE TITLE
Preserve workflow layout in UI when user leaves page

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#913]
Currently if a user leaves the workflow ui page and comes back the system redraws the layout overwriting any formatting that the user did.

**Comment by gtarcea** [comment]
It's currently unclear how the layout can be preserved.

**Comment by Terry-Weymouth** [comment]
@gtarcea I think that the best way  to do this is to add a user properties table. Then a layout type doc could have experiment id and x y coordinates for each process.
