### ISSUE TITLE
Add demo project for new users - phase 1

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#916]
When a new user creates an account create a cloned project that is an example for them to start working from. Allow the user to hide this example project.

The reason to create this is to show users what a project can look like and to give them an overview of the system.

Phase 1. Add an item to the user's options menu, top right, in nav-bar, to build/refresh demo project.

**Comment by Terry-Weymouth** [comment]
This issues reflects the basic script for building the demo project. In addition, it was necessary to make a number of extensions and corrections to the API to support the building of the demo script, Those are covered in a separate issue: #975
