### ISSUE TITLE
mcapi: add files recursively

### ISSUE THREAD

**Issue by bpuchala** [materials-commons/materialscommons.org#917]
It would be convenient to have a function that adds (uploads) files recursively from some local directory to some remote directory. Could be a member of Project, or Directory, or standalone? Then returns a list of File objects so they could be, for example, added to a Process.

Example:
```
def add_files_recursively(project, remote_dir, local_dirpath):
    """
    Arguments:
        project: mcapi.Project object
        remote_dir: mcapi.Directory object, where contents of local_dirpath 
            should be uploaded to
        local_dirpath: path to local directory to add files from, recursively
    
    Returns:
        files: List of mcapi.File objects
    """
    ... code ...
```

**Comment by Terry-Weymouth** [comment]
This is now covered by the API, the function name is different: (currently) Directory.add_directory_tree(dir_name,input_dir_path,verbose=False)
returns the base directory, updated.
