### ISSUE TITLE
In Create Sample - Composition - no feedback on Add Composition

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#920]
When initializing/editing the Create Sample process, when setting up the Composition of the samples, there is a visual ambiguity between Add (by which the user adds a Mineral to the Compound of the composition) and Add Composition (by which the user attaches the composition to the sample(s) generated by the process. In particular, there is no visual feed back that Add Composition has or has not been clicked. Also, labeling would help Add -> App element to Compound and Add Composition -> Attach Compound to Sample Composition.

**Comment by gtarcea** [comment]
Added a toast for success when button is clicked (we may need to do something else).
