### ISSUE TITLE
Cancel Process leaves process node in graph

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#921]
When the use is creating a workflow and clicks on a process (as if to add to the workflow graph) but then cancels the creation of the process, the process node is not removed from the graph/outline, and remains in the display of both. This is compounded by the fact that the display does not automatically update so the new (stray) node is not seen immediately. Once detected, the user's work around is to manually delete the node, but canceled nodes should be automatically deleted.

**Comment by gtarcea** [comment]
When cancel button is chosen have the UI tell the backend to delete the just created process.
