### ISSUE TITLE
Experiment Home's Samples Table needs cleanup

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#923]
On the project home page (and carrying over to the Experiment home page), the Tab Bar (with: Home, Experiments, Samples, Files, Settings), when clicking Samples shows the Samples Table. These are currently the headings of the columns of the table:  Sample (the sample name), Description, Composition, Modified (date), # Files, and # Processes. The Description can be removed (as the user has no way of setting or changing the description). The Composition always shows up as Unknown. I recommend that we remove the Description, and adding the compound information. Also, is we show Modified date, we need to update it when the sample is Modified - what ever that means.

**Comment by gtarcea** [comment]
Removed column.
