### ISSUE TITLE
Top Menu Bar (project home, experiment home) unnecessarily crouded 

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#924]
In the top level status/search bar (in the Project and Experiment home pages), the space between "MaterialsCommons" on the left and Search Project on the right is too crowded. I suggest that we condense the representation of the Samples, Users, and Publish Datasets, using the icons already in use on the Experiment Cards, for Samples, and Datasets - and add another for user(s).

**Comment by gtarcea** [comment]
Only show items depending on the screen size.
