### ISSUE TITLE
Task/Workflow Confusion of Template applicaiton

### ISSUE THREAD

**Issue by Terry-Weymouth** [materials-commons/materialscommons.org#926]
Currently the same set of Templates are used for workflow processes and tasks. This is confusing. Since all of the new Templates are focused on workflow processes, I suggest that we decorate theTask templet(s) with an internal flag, have just one Task template for now, and comment out all Template selection for Tasks.

**Comment by gtarcea** [comment]
Tasks are no longer processes.
