### ISSUE TITLE
Manufacturing Date on "Add new Samples"

### ISSUE THREAD

**Issue by tradiasa** [materials-commons/materialscommons.org#935]
![screenshot](https://cloud.githubusercontent.com/assets/25109883/21945238/227864fa-d9a8-11e6-9a7c-757fc593cae9.png)

If you click on the calendar button to add the date, it defaults to Sept 1933.

**Comment by Terry-Weymouth** [comment]
Got it. Thanks. (I noticed this also - default of 'today' would be a lot better). Thanks for issue.

**Comment by Terry-Weymouth** [comment]
Fixed via commit 6ad0d25.

**Comment by Terry-Weymouth** [comment]
@tradiasa - fixed this problem; change will be available in next release at end of January 2017.
