### ISSUE TITLE
Template Update for EBSD Data Collection

### ISSUE THREAD

**Issue by tradiasa** [materials-commons/materialscommons.org#937]
Scan size should allow for 2 dimensions, height and width (for example: 500 x 1200 µm).  Right now "scan size" only accepts a single numerical value.  

We should also include something in the template that notes orientation. For example, someone looking at a rolled sheet would want to note whether the rolling direction is vertical, horizontal, or if they just stuck it in willy nilly.  

I think we'd want text fields that prompt:
horizontal direction:
vertical direction:

So for one of my scans I might use:
horizontal direction: short transverse
vertical direction: long transverse

There are a lot of fields in this template I don't think are necessary (current, sample tilt, magnification, acquisition time...); however, I'm assuming someone did at one point so we can leave them there until we get more feedback.

**Comment by gtarcea** [comment]
Added requested fields for horizontal and vertical direction. Due to limited types I broke scan size into two attributes: Scan Size Height and Scan Size Width. This required adding a conversion for existing scan size properties.
