### ISSUE TITLE
Suggested change to linking files & samples

### ISSUE THREAD

**Issue by tradiasa** [materials-commons/materialscommons.org#940]
![screenshot](https://cloud.githubusercontent.com/assets/25109883/22080818/00658b64-dd8f-11e6-8186-8f250000dc26.png)

It would be easier to use checkboxes to link samples to a file, than to have to link the same file to each sample, which is what I need to do in the screenshot above.  All samples used in the process should be linked to the L124_photo.  When choosing which samples to link, you can filter down to only include those used in the process.

**Comment by gtarcea** [comment]
Added the ability to link from a file. This makes it easier to link an individual file to a set of samples.
