### ISSUE TITLE
Published datasets zipfiles are not automatically built

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#950]
Currently when publishing a dataset the zip files are not built automatically. Instead we have to manually run a script to build the dataset.

For the short term I propose launching the script in the background to publish a dataset. There are some timing issues such as if someone publishes, unpublishes and then publishes again quickly, then there will be two builds running. If there were changes in between then it is non-deterministic which version of the dataset zipfile would be published. Still, for a short term work around this would get us out of having to manually build the zipfiles.

**Comment by Terry-Weymouth** [comment]
There is now a background task server, mcmon, that watches for publication changes and launches the zip file build when a publication is made, and removes the zip file when a publication is unpublished. See background/serves/mcmon, specifically .../src/publication-watcher.js
