### ISSUE TITLE
Materials Commons Get's Hung Up when you click on .xlsx items in files

### ISSUE THREAD

**Issue by tradiasa** [materials-commons/materialscommons.org#955]
<img width="522" alt="screenshot" src="https://cloud.githubusercontent.com/assets/25109883/22341576/52bccba8-e3bf-11e6-9f15-5d0e4cbc9be2.png">

<img width="1292" alt="screenshot" src="https://cloud.githubusercontent.com/assets/25109883/22341619/7c839b24-e3bf-11e6-8c2a-64232e2682d5.png">

If I go to files and click on "Berman_Lift380_L124_20161227.xlsx" the page becomes unresponsive.  (This is in the Lift Melt 5b in reg. MC).

It also happened when I tried to open a .xlsx file in Erin's project (also reg MC).

**Comment by gtarcea** [comment]
System wasn't recognizing certain files as excel (or word, or powerpoint files). Updated check so it doesn't attempt to display them.
