### ISSUE TITLE
Create Samples: Add multiple samples

### ISSUE THREAD

**Issue by tradiasa** [materials-commons/materialscommons.org#976]
There is no obvious order to the samples created.  I would think there should be some way to sort by alphabetical or numerical order.  See screenshot below, I created 30 samples named 7075 plate_$Index.

<img width="693" alt="screenshot" src="https://cloud.githubusercontent.com/assets/25109883/23032133/81516dce-f441-11e6-8c48-56ff6e5677f8.png">
 or numerical order.

**Comment by gtarcea** [comment]
Sort by sample name. This causes new sample entry (when hitting return) to float to the top.
