### ISSUE TITLE
Heat Treatment Template will not let you add multiple input samples (test site)

### ISSUE THREAD

**Issue by tradiasa** [materials-commons/materialscommons.org#977]
I might want to heat treat a batch of samples (7075 plate_10 and 7075 plate_11), right now I can only pick 1.  

<img width="1042" alt="screenshot" src="https://cloud.githubusercontent.com/assets/25109883/23032486/7c773f08-f442-11e6-86a0-a3f336867683.png">

**Comment by gtarcea** [comment]
There was old code that was only allowing a single sample to be selected. I removed this check.
