### ISSUE TITLE
UI Cleanup - Needs to be reviewed

### ISSUE THREAD

**Issue by gtarcea** [materials-commons/materialscommons.org#991]
* when creating a process & adding files
    * no way to search for files
    * file names truncated
* when you create a new pre-filled process, it’s not showing up
* drop downs may not be saving in pre-filled templates (hard to check with above issue, but my old pre-filled are empty now)
* on processes
    * says “no samples” when there are samples
    * defaults to show input files, might be sad for experimentalists
    * don’t necessarily want to display all of contents of txt file, you have to scroll down a lot, clip part and add “show more” pop-up option?
    * shows chemistry beaker for 3 transformations, but not clickable to find out what those transformations are
    * 
* home page
    * like that buttons are clickable
* cancel button not working!

dismiss ADD pop-up after selecting process
on the tabular view of workflow
change icons so they don't resemble files and folders
advanced: allow you to select process (or processes) in the tabular view to filter down what is shown on the graphical workflow view
when picking samples to add as input, add the option to click on the sample and see the same view you would find in the "samples" tab (linked files, timeline...)
it is more intuitive for me to double click on a process to see details than to right click...
however I'd like to right click to be able to add a downstream process from the current process (for example: right click on a "create samples process" to bring up the ADD pop-up which lets me choose a transformation (section)
it would be nice to be able to "star/favorite" templates so that they show up on the top of the list (for example: under transformations, I'd personally like "section" to show up first.  Having starred options on top is faster than searching, if you only have a few favorites
for some reason it's not letting me select an input sample for sectioning on the test site.  Maybe that's just a bug?  It works if I try cogging as the transformation process.

**Comment by Terry-Weymouth** [comment]
I propose that this be reviewed in June for (possible) further action and that actionable issues be separated out and scheduled.
